### ISSUE TITLE
Publish on PyPI?

### ISSUE THREAD

**Issue by rouge8** [Yelp/docker-custodian#10]
Are there plans to publish docker-custodian on PyPI?

**Comment by dnephin** [comment]
I think that would be a good idea

**Comment by dwlocks** [comment]
I was just about to ask if you'd be interested in a patch that made the package more pypi-ish and less debian-ish.  I can probably tweak the debian package to still work, but my deb package skills are a tad rusty.

Mostly this would be to  use setup.py  infrastructure to install the scripts instead of debian package links.  Perhaps I'll investigate whl style packages?

**Comment by dnephin** [comment]
Isn't this already done by https://github.com/Yelp/docker-custodian/blob/master/setup.py#L29 ?

If I install this package using `pip` it should correctly install the executables.

**Comment by dwlocks** [comment]
oh you're right!  I just saw the debian/ stuff and didn't check setup.py.  nm.

**Comment by hashbrowncipher** [comment]
@solarkennedy might I ask why this was closed? As a user, I would like docker-custodian to be as easily accessible as my other docker utilities (e.g. docker-compose).

**Comment by solarkennedy** [comment]
This package is on pypi and will deployed there automatically with each tagged release.

**Comment by hashbrowncipher** [comment]
👍 !
